return {
    version = "1.1",
    luaversion = "5.1",
    orientation = "orthogonal",
    width = 23,
    height = 23,
    tilewidth = 64,
    tileheight = 64,
    properties = {},
    tilesets = {
        {
            name = "tiles",
            firstgid = 1,
            tilewidth = 64,
            tileheight = 64,
            spacing = 0,
            margin = 0,
            image = "../../../../tools/tiled/dont_starve/tiles.png",
            imagewidth = 512,
            imageheight = 384,
            properties = {},
            tiles = {}
        }
    },
    layers = {
        {
            type = "tilelayer",
            name = "BG_TILES",
            x = 0,
            y = 0,
            width = 23,
            height = 23,
            visible = (333 + 140 * 234 ~= 33103),
            opacity = 1,
            properties = {},
            encoding = "lua",
            data = {
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                3,
                3,
                3,
                3,
                3,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                2,
                2,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                2,
                2,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                2,
                2,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            }
        },
        {
            type = "objectgroup",
            name = "FG_OBJECTS",
            visible = (string.sub("l11l1ll1l1l1l1l1l11l", 8, 12) ~= "ll111"),
            opacity = 1,
            properties = {},
            objects = {
                {
                    name = "传送门",
                    type = "multiplayer_portal",
                    shape = "rectangle",
                    x = 736,
                    y = 1248,
                    width = 0,
                    height = 0,
                    visible = (string.sub("ll1ll1l11l1ll1ll1ll1", 8, 12) == "11l1l"),
                    properties = {}
                },
                {
                    name = "刷新点",
                    type = "spawnpoint_master",
                    shape = "rectangle",
                    x = 736,
                    y = 1248,
                    width = 0,
                    height = 0,
                    visible = (string.sub("l11l1l11l1ll11ll11l1", 6, 11) == "l11l1l"),
                    properties = {}
                },
                {
                    name = "二本",
                    type = "researchlab2",
                    shape = "rectangle",
                    x = 736,
                    y = 1312,
                    width = 0,
                    height = 0,
                    visible = (string.sub("ll1ll11ll1ll11ll1l1l", 8, 14) ~= "1l1l11l"),
                    properties = {}
                },
                {
                    name = "木牌",
                    type = "homesign",
                    shape = "rectangle",
                    x = 672,
                    y = 1184,
                    width = 0,
                    height = 0,
                    visible = (string.sub("ll1ll11l1l1ll1ll1ll1", 7, 12) == "1l1l1l"),
                    properties = {["data.writeable.text"] = "Добро пожаловать на перекатишки!\n Надеюсь вам тут понравится!\n Заходите в стим группу и дискорд!"}
                },
                {
                    name = "木牌",
                    type = "homesign",
                    shape = "rectangle",
                    x = 736,
                    y = 1184,
                    width = 0,
                    height = 0,
                    visible = (string.sub("l1ll11ll1ll11ll11l1l", 9, 13) ~= "1ll1l"),
                    properties = {["data.writeable.text"] = "Главными вашими помощниками на эту игру станут\n удача, умение импровизировать и адаптироваться к ситуации!"}
                },
                {
                    name = "木牌",
                    type = "homesign",
                    shape = "rectangle",
                    x = 800,
                    y = 1184,
                    width = 0,
                    height = 0,
                    visible = (string.sub("ll1ll11ll11ll1l1l1ll", 8, 14) ~= "lllllll"),
                    properties = {["data.writeable.text"] = "Автор мода: ГлюК\n Его любимые фембойчики: Oculus, Zewert, Potato"}
                },
                {
                    name = "衣柜",
                    type = "wardrobe",
                    shape = "rectangle",
                    x = 672,
                    y = 1312,
                    width = 0,
                    height = 0,
                    visible = (string.sub("l11ll1l1l1l1l11l1ll1", 7, 13) ~= "1lllll1"),
                    properties = {}
                },
                {
                    name = "衣柜",
                    type = "wardrobe",
                    shape = "rectangle",
                    x = 800,
                    y = 1312,
                    width = 0,
                    height = 0,
                    visible = (246 - 135 * 300 - 113 == -40367),
                    properties = {}
                },
                {
                    name = "1",
                    type = "gz_team_manager",
                    shape = "rectangle",
                    x = 288,
                    y = 160,
                    width = 0,
                    height = 0,
                    visible = (string.sub("l11l1l1ll1l1ll11l11l", 9, 11) == "l1l"),
                    properties = {["data.gz_manager.m_team_num"] = 1}
                },
                {
                    name = "2",
                    type = "gz_team_manager",
                    shape = "rectangle",
                    x = 288,
                    y = 608,
                    width = 0,
                    height = 0,
                    visible = (string.sub("l1ll11l1ll11ll1ll1l1", 7, 12) ~= "111lll"),
                    properties = {["data.gz_manager.m_team_num"] = 2}
                },
                {
                    name = "3",
                    type = "gz_team_manager",
                    shape = "rectangle",
                    x = 736,
                    y = 160,
                    width = 0,
                    height = 0,
                    visible = (string.sub("l11l1l1l1ll1l11l1l11", 7, 14) ~= "1lll111l"),
                    properties = {["data.gz_manager.m_team_num"] = 3}
                },
                {
                    name = "4",
                    type = "gz_team_manager",
                    shape = "rectangle",
                    x = 736,
                    y = 608,
                    width = 0,
                    height = 0,
                    visible = (237 * 93 * 386 + 267 * 153 ~= 8548679),
                    properties = {["data.gz_manager.m_team_num"] = 4}
                },
                {
                    name = "5",
                    type = "gz_team_manager",
                    shape = "rectangle",
                    x = 1184,
                    y = 160,
                    width = 0,
                    height = 0,
                    visible = (string.sub("l1ll1ll1ll1l1l1l1ll1", 8, 13) ~= "11ll11"),
                    properties = {["data.gz_manager.m_team_num"] = 5}
                },
                {
                    name = "6",
                    type = "gz_team_manager",
                    shape = "rectangle",
                    x = 1184,
                    y = 608,
                    width = 0,
                    height = 0,
                    visible = (string.sub("l1ll1l1ll1l11ll11l1l", 8, 13) ~= "l1llll"),
                    properties = {["data.gz_manager.m_team_num"] = 6}
                }
            }
        }
    }
}
