TUNING["DC_FGC_TTS"] =(103 * 374 * 439 == 16911158)

TUNING["gz_GameMode"] = GetModConfigData "gz_GameMode"
TUNING["gz_SpecialModeStartTime"] = GetModConfigData "gz_SpecialModeStartTime"
TUNING["gz_ContinueSpawnGrass"] = GetModConfigData "gz_ContinueSpawnGrass"
TUNING["gz_TeamDamageCoefficient"] = GetModConfigData "gz_TeamDamageCoefficient"
TUNING["gz_Site"] = GetModConfigData "gz_Site"
TUNING["GZ_ShowName"] = GetModConfigData "GZ_ShowName"
TUNING["GZ_COUNT_WEED_MAX"] = GetModConfigData "GZ_COUNT_WEED_MAX"
TUNING["GZ_NUM_WEED"] = GetModConfigData "GZ_NUM_WEED"
TUNING["GZ_GHOST_TIME_MAX"] = GetModConfigData "GZ_GHOST_TIME_MAX"
TUNING["GZ_AUTO_SPAWN_PERIOD"] = GetModConfigData "GZ_AUTO_SPAWN_PERIOD"
TUNING["GZ_AUTO_SPAWN_CUT"] = GetModConfigData "GZ_AUTO_SPAWN_CUT"
TUNING["GZ_RandomChar"] = GetModConfigData "GZ_RandomChar"
TUNING["GZ_nishuitaotai"] = GetModConfigData "GZ_nishuitaotai"
TUNING["GZ_zhandoutaozhuang"] = GetModConfigData "GZ_zhandoutaozhuang"

local ll1ll1l1l11l11ll11ll = 30

TUNING["DAY_SEGS_DEFAULT"] = 14
TUNING["DUSK_SEGS_DEFAULT"] = 0
TUNING["NIGHT_SEGS_DEFAULT"] = 2
TUNING["DAY_TIME_DEFAULT"] = ll1ll1l1l11l11ll11ll * TUNING["DAY_SEGS_DEFAULT"]
TUNING["DUSK_TIME_DEFAULT"] = ll1ll1l1l11l11ll11ll * TUNING["DUSK_SEGS_DEFAULT"]
TUNING["NIGHT_TIME_DEFAULT"] = ll1ll1l1l11l11ll11ll * TUNING["NIGHT_SEGS_DEFAULT"]
TUNING["TELESTAFF_USES"] = 1
TUNING["ORANGESTAFF_USES"] = 1
TUNING["PANFLUTE_USES"] = 2
TUNING["TORNADOSTAFF_USES"] = 7
TUNING["EYETURRET_HEALTH"] = 1000
TUNING["EYETURRET_REGEN"] = 2
TUNING["EYETURRET_RANGE"] = 8
TUNING["EYETURRET_DAMAGE"] = 65
TUNING["TENT_USES"] = 1
TUNING["SIESTA_CANOPY_USES"] = 1
TUNING["YELLOWSTAFF_USES"] = 6
TUNING["OPALSTAFF_USES"] = 3
TUNING["GREENSTAFF_USES"] = 3
TUNING["FUSED_SHADELING_HEALTH"] = 800
TUNING["STAFF_LUNARPLANT_USES"] = 25
TUNING["BOOMERANG_USES"] = 4
TUNING["BOOMERANG_DAMAGE"] = 200
TUNING["BOOMERANG_DISTANCE"] = 70
TUNING["GZ_RANGE_BLOWDARTS"] = 70
TUNING["GZ_DAMAGE_BLOWDART_SLEEP"] = 0
TUNING["GZ_DAMAGE_BLOWDART_FIRE"] = 0
TUNING["GZ_DAMAGE_BLOWDART_PIPE"] = 100
TUNING["GZ_DAMAGE_BLOWDART_YELLOW"] = 100
TUNING["GZ_RANGE_STAFFS"] = 70
TUNING["GZ_DAMAGE_ICESTAFF"] = 1
TUNING["GZ_DAMAGE_FIRESTAFF"] = 0
TUNING["FIRESTAFF_USES"] = 10
TUNING["ICESTAFF_USES"] = 10
TUNING["GZ_RANGE_BOMBS"] = 70
TUNING["GZ_DAMAGE_SLEEPBOMB"] = 20
TUNING["GZ_DAMAGE_BOMB_LUNARPLANT"] = 20
TUNING["BOMB_LUNARPLANT_PLANAR_DAMAGE"] = 200

if ACTIONS["TOSS"] ~= nil and TUNING["GZ_RANGE_BOMBS"] ~= nil then
    ACTIONS["TOSS"]["distance"] = TUNING["GZ_RANGE_BOMBS"]

end

TUNING["GZ_RANGE_CASTSPELL"] = 70

if ACTIONS["CASTSPELL"] ~= nil and TUNING["GZ_RANGE_CASTSPELL"] ~= nil then
    ACTIONS["CASTSPELL"]["distance"] = TUNING["GZ_RANGE_CASTSPELL"]

end

TUNING["BEARGER_HEALTH"] = 2500
TUNING["MOOSE_HEALTH"] = 3000
TUNING["DRAGONFLY_HEALTH"] = 2300
TUNING["DEERCLOPS_HEALTH"] = 3000
TUNING["ANTLION_HEALTH"] = 1500
TUNING["TOADSTOOL_HEALTH"] = 2888
TUNING["TOADSTOOL_DARK_HEALTH"] = 99998
TUNING["BEEQUEEN_HEALTH"] = 1234
TUNING["STALKER_ATRIUM_HEALTH"] = 17501
TUNING["STALKER_HEALTH"] = 3777
TUNING["KLAUS_HEALTH"] = 1800
TUNING["MINOTAUR_HEALTH"] = 4444
TUNING["MALBATROSS_HEALTH"] = 3000
TUNING["ALTERGUARDIAN_PHASE1_HEALTH"] = 1000
TUNING["ALTERGUARDIAN_PHASE2_STARTHEALTH"] = 600
TUNING["ALTERGUARDIAN_PHASE3_STARTHEALTH"] = 1000
TUNING["DAYWALKER_HEALTH"] = 1000
TUNING["SHADOWTHRALL_HANDS_HEALTH"] = 800
TUNING["SHADOWTHRALL_HORNS_HEALTH"] = 555
TUNING["SHADOWTHRALL_WINGS_HEALTH"] = 800
TUNING["EYEOFTERROR_HEALTH"] = 1800
TUNING["TALLBIRD_HEALTH"] = 600
TUNING["SLURPER_HEALTH"] = 500
TUNING["MERMHOUSE_MERMS"] = 2
TUNING["MERMHOUSE_EMERGENCY_MERMS"] = 2

local ll1l11l1ll1l1l11ll1l = 350

local l1ll1l1l1ll1ll1l1ll1 = 700

local l11ll11ll1l1ll1ll1ll = 1500

local ll11l1ll1ll11ll1l1l1 = 350

local l11ll11l11l11l1ll11l = 700

local l11l11l1ll1l1l1l1l1l = 1500

local l1l1l1l1ll1l11l11l11 = 350

local ll1l1l1l1ll1ll1ll1ll = 700

local l1ll11ll1ll1l1ll1l11 = 1500

TUNING["SHADOW_KNIGHT"]["HEALTH"] ={ll1l11l1ll1l1l11ll1l, l1ll1l1l1ll1ll1l1ll1, l11ll11ll1l1ll1ll1ll}
TUNING["SHADOW_ROOK"]["HEALTH"] ={ll11l1ll1ll11ll1l1l1, l11ll11l11l11l1ll11l, l11l11l1ll1l1l1l1l1l}
TUNING["SHADOW_BISHOP"]["HEALTH"] ={l1l1l1l1ll1l11l11l11, ll1l1l1l1ll1ll1ll1ll, l1ll11ll1ll1l1ll1l11}
TUNING["MIASMA_SPACING"] = 1.1